# Default values for Deimo ArgoCD app.

namespace: deimos
replicaCount: 1

image:
  repository: registry.gitlab.com/k8s45/deimos
  pullPolicy: Always
  tag: 0.0.3

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  webPort: 30009
