---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deimos-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get", "list"]
  