---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-np"
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: port-queue
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.webPort }}
